version: '3.8'

services:
  postgres_test:
    image: postgres:15-alpine
    container_name: eventix_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventix_test_db
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redpanda_test:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: eventix_redpanda_test
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29093,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr PLAINTEXT://redpanda_test:29093,OUTSIDE://localhost:9093
    ports:
      - "9093:9093"
      - "8083:8081"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health"]
      interval: 5s
      timeout: 5s
      retries: 5
